### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by fahrettine** [cvlab-ai/cvlab#1]
Hi all,
I run "sudo pip3 install --upgrade cvlab" command on Terminal.
I get the error below.
Any idea? Thanks...
- OS:  Debian 64 bit
- OpenCV 3.2.0
*******************************************************************************

  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-hrjsql_z/pyqt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-hrjsql_z/pyqt5/

**Comment by ambrzeski** [comment]
What is your pip version? You could try upgrading:

```pip3 install --upgrade pip```

**Comment by jachoo** [comment]
It looks there is a problem with PyQt5 package.

The simplest workaround is probably to install PyQt5 from system repository: `sudo apt-get install python3-pyqt5`

Take a look at:

- https://stackoverflow.com/questions/59711301/install-pyqt5-5-14-1-on-linux
- https://stackoverflow.com/questions/59768179/pip-raise-filenotfounderror-errno-2-no-such-file-or-directory-tmp-pip-inst

Please tell me if it helps, so I can close the issue.
